=== sdpython/pyrsslocal/_unittests/ut_xmlhelper/data/debvisdic-strict.dtd
<!-- DTD for DEBVISDIC format of Wordnet -->
<!ELEMENT WN (SYNSET+)>
<!ELEMENT sl.dbxml (SYNSET+)>
<!ELEMENT SYNSET (STAMP?, ILR*, SUMO*, G_SYN?, ID, SYNONYM, DEF, USAGE*, SNOTE?, BCS?, DOMAIN?, NL*, POS)>
<!--ELEMENT SYNSET (ID | POS | SYNONYM | ILR | DEF | USAGE | SNOTE | BCS | DOMAIN | NL | SUMO | G_SYN | STAMP)+ -->
<!ELEMENT ID (#PCDATA)>
<!ELEMENT POS (#PCDATA)>
<!ELEMENT SYNONYM (LITERAL | WORD)+>
<!ELEMENT LITERAL (#PCDATA)>
<!ATTLIST LITERAL
          lnote CDATA #IMPLIED
          sense CDATA #IMPLIED>
<!ELEMENT WORD (#PCDATA)>
<!ELEMENT ILR (#PCDATA)>
<!ATTLIST ILR
          type CDATA #REQUIRED>
<!ELEMENT DEF (#PCDATA)>
<!ELEMENT USAGE (#PCDATA)>
<!ELEMENT SNOTE (#PCDATA)>
<!ELEMENT BCS (#PCDATA)>
<!ELEMENT DOMAIN (#PCDATA)>
<!ELEMENT NL (#PCDATA)>
<!ELEMENT SUMO (#PCDATA)>
<!ATTLIST SUMO
          type CDATA #REQUIRED>
<!ELEMENT G_SYN (#PCDATA)>
<!ELEMENT STAMP (#PCDATA)>

=== sdpython/pyrsslocal/_unittests/ut_xmlhelper/data/sample.wolf.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE WN SYSTEM "debvisdic-strict.dtd">
<WN>
<SYNSET><ILR type="near_antonym">eng-30-00002098-a</ILR><ILR type="be_in_state">eng-30-05200169-n</ILR><ILR type="be_in_state">eng-30-05616246-n</ILR><ILR type="eng_derivative">eng-30-05200169-n</ILR><ILR type="eng_derivative">eng-30-05616246-n</ILR><ID>eng-30-00001740-a</ID><SYNONYM><LITERAL lnote="2/2:fr.csbgen,fr.csen">comptable</LITERAL></SYNONYM><DEF>(usually followed by `to') having the necessary means or skill or know-how or authority to do something</DEF><USAGE>able to swim</USAGE><USAGE>she was able to program her computer</USAGE><USAGE>we were at last able to buy a car</USAGE><USAGE>able to get a grant for the project</USAGE><BCS>3</BCS><POS>a</POS></SYNSET>
<SYNSET><ID>eng-30-00001740-b</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>without musical accompaniment</DEF><USAGE>they performed a cappella</USAGE><POS>b</POS></SYNSET>
<SYNSET><ID>eng-30-00001740-n</ID><SYNONYM><LITERAL lnote="96/4:fr.csen,fr.rocsen,fr.roen,enwikipedia;gwa2012(0.86013904790866246852);lrec12mllexwn(1.548);ManVal2012OK">entité</LITERAL></SYNONYM><DEF>concept formulant la catégorisation et l'identique des choses de notre environnement</DEF><BCS>2</BCS><POS>n</POS></SYNSET>
<SYNSET><ILR type="subevent">eng-30-00004227-v</ILR><ILR type="subevent">eng-30-00005041-v</ILR><ILR type="also_see">eng-30-00004227-v</ILR><ILR type="also_see">eng-30-00005041-v</ILR><ILR type="verb_group">eng-30-00002325-v</ILR><ILR type="verb_group">eng-30-00002573-v</ILR><ILR type="eng_derivative">eng-30-00831191-n</ILR><ILR type="eng_derivative">eng-30-03110322-a</ILR><ILR type="eng_derivative">eng-30-04080833-n</ILR><ILR type="eng_derivative">eng-30-04250850-n</ILR><ID>eng-30-00001740-v</ID><SYNONYM><LITERAL lnote="gwa2012(0.11494434591511053234);lrec12mllexwn(1.219)">inspirer</LITERAL><LITERAL lnote="lrec12mllexwn(4.094)">respirer</LITERAL></SYNONYM><DEF>draw air into, and expel out of, the lungs</DEF><USAGE>I can breathe better when the air is clean</USAGE><USAGE>The patient is respiring</USAGE><BCS>3</BCS><POS>v </POS></SYNSET>
<SYNSET><ID>eng-30-00001837-b</ID><SYNONYM><LITERAL lnote="ManVal2008OK;0/1:enwiktionary">ap. J.-C.</LITERAL><LITERAL lnote="ManValOK:0/1:enwiktionary">ap. JC</LITERAL><LITERAL lnote="lrec12mllexwn(1.406)">apr. J.-C.</LITERAL><LITERAL lnote="ManValOK:0/1:enwiktionary">après JC</LITERAL><LITERAL lnote="ManValOK:0/1:enwiktionary;lrec12mllexwn(1.266)">après Jésus-Christ</LITERAL></SYNONYM><DEF>in the Christian era; used before dates after the supposed year Christ was born</DEF><USAGE>in AD 200</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001740-n</ILR><ID>eng-30-00001930-n</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>an entity that has physical existence</DEF><POS>n</POS></SYNSET>
<SYNSET><ID>eng-30-00001981-b</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>of the period coinciding with the Christian era; preferred by some writers who are not Christians</DEF><USAGE>in 200 CE</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00001740-a</ILR><ILR type="be_in_state">eng-30-05200169-n</ILR><ID>eng-30-00002098-a</ID><SYNONYM><LITERAL lnote="gwa2012(0.21239273529164556797);lrec12mllexwn(1.246)">incapable</LITERAL></SYNONYM><DEF>(usually followed by `to') not having the necessary means or skill or know-how</DEF><USAGE>unable to get to town without a car</USAGE><USAGE>unable to obtain funds</USAGE><BCS>3</BCS><POS>a</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001740-n</ILR><ILR type="eng_derivative">eng-30-00692329-v</ILR><ID>eng-30-00002137-n</ID><SYNONYM><LITERAL lnote="lrec12mllexwn(1.568);ManVal2012OK">abstraction</LITERAL></SYNONYM><DEF>a general concept formed by extracting common features from specific examples</DEF><BCS>2</BCS><POS>n</POS></SYNSET>
<SYNSET><ID>eng-30-00002142-b</ID><SYNONYM><LITERAL lnote="lrec12mllexwn(1.309)">av. J.-C.</LITERAL></SYNONYM><DEF>before the Christian era; used following dates before the supposed year Christ was born</DEF><USAGE>in 200 BC</USAGE><POS>b</POS></SYNSET>
<SYNSET><ID>eng-30-00002296-b</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>of the period before the Common Era; preferred by some writers who are not Christians</DEF><USAGE>in 200 BCE</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00002527-a</ILR><ILR type="category_domain">eng-30-06037666-n</ILR><ID>eng-30-00002312-a</ID><SYNONYM><LITERAL lnote="0/1:frwiktionary;gwa2012(0.23213043465120136721)">abaxial</LITERAL></SYNONYM><DEF>facing away from the axis of an organ or organism</DEF><USAGE>the abaxial surface of a leaf is the underside or side facing away from the stem</USAGE><POS>a</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-02108377-v</ILR><ILR type="verb_group">eng-30-00001740-v</ILR><ILR type="eng_derivative">eng-30-00830811-n</ILR><ILR type="eng_derivative">eng-30-00831191-n</ILR><ILR type="eng_derivative">eng-30-03110322-a</ILR><ID>eng-30-00002325-v</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>undergo the biomedical and metabolic processes of respiration by taking up oxygen and producing carbon monoxide</DEF><POS>v</POS></SYNSET>
<SYNSET><ID>eng-30-00002436-b</ID><SYNONYM><LITERAL lnote="lrec12mllexwn(1.398)">à cheval</LITERAL></SYNONYM><DEF>on the back of a horse</DEF><USAGE>he rode horseback to town</USAGE><USAGE>managed to escape ahorse</USAGE><USAGE>policeman patrolled the streets ahorseback</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001930-n</ILR><ID>eng-30-00002452-n</ID><SYNONYM><LITERAL lnote="gwa2012(0.10704234483284695567)">cause</LITERAL><LITERAL lnote="gwa2012(0.44201245509806086353);lrec12mllexwn(1.651)">chose</LITERAL><LITERAL lnote="gwa2012(0.11657436313981721365);lrec12mllexwn(2.845)">objet</LITERAL></SYNONYM><DEF>a separate and self-contained entity</DEF><BCS>3</BCS><POS>n</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00002312-a</ILR><ILR type="category_domain">eng-30-06037666-n</ILR><ID>eng-30-00002527-a</ID><SYNONYM><LITERAL lnote="lrec12mllexwn(1.481)">ventral</LITERAL></SYNONYM><DEF>nearest to or facing toward the axis of an organ or organism</DEF><USAGE>the upper side of a leaf is known as the adaxial surface</USAGE><POS>a</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001740-v</ILR><ILR type="verb_group">eng-30-00001740-v</ILR><ILR type="eng_derivative">eng-30-03110322-a</ILR><ID>eng-30-00002573-v</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>breathe easily again, as after exertion or anxiety</DEF><POS>v</POS></SYNSET>
<SYNSET><ID>eng-30-00002621-b</ID><SYNONYM><LITERAL lnote="lrec12clwolf(2.1757);lrec12mllexwn(1.201)">guère</LITERAL><LITERAL lnote="lrec12mllexwn(3.953)">à peine</LITERAL></SYNONYM><DEF>only a very short time before</DEF><USAGE>they could barely hear the speaker</USAGE><USAGE>we hardly knew them</USAGE><USAGE>just missed being hit</USAGE><USAGE>had scarcely rung the bell when the door flew open</USAGE><USAGE>would have scarce arrived before she would have found some excuse to leave (W.B.Yeats)</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001930-n</ILR><ILR type="eng_derivative">eng-30-00532607-v</ILR><ID>eng-30-00002684-n</ID><SYNONYM><LITERAL lnote="gwa2012(0.11751675742438526251);lrec12mllexwn(1.315);ManVal2012AN">chose</LITERAL><LITERAL lnote="65/5:fr.csbgen,fr.csen,fr.rocsbgen,fr.rocsen,fr.roen;gwa2012(0.47707899674865983375);lrec12mllexwn(1.698);ManVal2012OK">objet</LITERAL></SYNONYM><DEF>a tangible and visible entity; an entity that can cast a shadow</DEF><USAGE>it was full of rackets, balls and other objects</USAGE><BCS>1</BCS><POS>n</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001740-v</ILR><ILR type="eng_derivative">eng-30-14058252-n</ILR><ID>eng-30-00002724-v</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>breathe with great difficulty, as when experiencing a strong emotion</DEF><USAGE>She choked with emotion when she spoke about her deceased husband</USAGE><POS>v</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00002843-a</ILR><ILR type="category_domain">eng-30-06066555-n</ILR><ID>eng-30-00002730-a</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>facing or on the side toward the apex</DEF><POS>a</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00002730-a</ILR><ILR type="category_domain">eng-30-06066555-n</ILR><ID>eng-30-00002843-a</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>facing or on the side toward the base</DEF><POS>a</POS></SYNSET>
<SYNSET><ILR type="hypernym">eng-30-00001740-v</ILR><ILR type="verb_group">eng-30-00003133-v</ILR><ILR type="eng_derivative">eng-30-00833870-n</ILR><ID>eng-30-00002942-v</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>breathe excessively hard and fast</DEF><USAGE>The mountain climber started to hyperventilate</USAGE><POS>v</POS></SYNSET>
<SYNSET><ID>eng-30-00002950-b</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>exactly at this moment or the moment described</DEF><USAGE>None</USAGE><POS>b</POS></SYNSET>
<SYNSET><ILR type="near_antonym">eng-30-00003131-a</ILR><ILR type="category_domain">eng-30-06080522-n</ILR><ID>eng-30-00002956-a</ID><SYNONYM><LITERAL>_EMPTY_</LITERAL></SYNONYM><DEF>especially of muscles; drawing away from the midline of the body or from an adjacent part</DEF><POS>a</POS></SYNSET>
<SYNSET><ILR type="derived">eng-30-00016756-a</ILR><ID>eng-30-00003093-b</ID><SYNONYM><LITERAL lnote="lrec12clwolf(2.3092)">difficilement</LITERAL><LITERAL lnote="lrec12clwolf(2.3092);lrec12mllexwn(1.201)">guère</LITERAL><LITERAL lnote="lrec12clwolf(2.3092)">pratiquement</LITERAL><LITERAL lnote="lrec12mllexwn(1.356)">à peine</LITERAL></SYNONYM><DEF>almost not</DEF><USAGE>he hardly ever goes fishing</USAGE><USAGE>he was hardly more than sixteen years old</USAGE><USAGE>they scarcely ever used the emergency generator</USAGE><POS>b</POS></SYNSET>
